/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "protocols.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(isppipeline_CaptureImageCommand, isppipeline_CaptureImageCommand, AUTO)


PB_BIND(isppipeline_ReadISPParametersCommand, isppipeline_ReadISPParametersCommand, AUTO)


PB_BIND(isppipeline_WriteISPParametersCommand, isppipeline_WriteISPParametersCommand, AUTO)


PB_BIND(isppipeline_BLCParameters, isppipeline_BLCParameters, AUTO)


PB_BIND(isppipeline_CCMParameters, isppipeline_CCMParameters, AUTO)


PB_BIND(isppipeline_GammaParameters, isppipeline_GammaParameters, AUTO)


PB_BIND(isppipeline_ISPParameters, isppipeline_ISPParameters, AUTO)


PB_BIND(isppipeline_ISPParametersResponse, isppipeline_ISPParametersResponse, AUTO)


PB_BIND(isppipeline_ImageResponse, isppipeline_ImageResponse, AUTO)


PB_BIND(isppipeline_DataPacket, isppipeline_DataPacket, AUTO)




