# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/protocols.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protobuf/protocols.proto\x12\x0bisppipeline\"E\n\x13\x43\x61ptureImageCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\"+\n\x18ReadISPParametersCommand\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"Y\n\rISPParameters\x12\x10\n\x08r_offset\x18\x01 \x01(\x02\x12\x11\n\tgr_offset\x18\x02 \x01(\x02\x12\x11\n\tgb_offset\x18\x03 \x01(\x02\x12\x10\n\x08\x62_offset\x18\x04 \x01(\x02\"h\n\x15ISPParametersResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\nparameters\x18\x03 \x01(\x0b\x32\x1a.isppipeline.ISPParameters\"\xa8\x01\n\rImageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x12\r\n\x05width\x18\x04 \x01(\r\x12\x0e\n\x06height\x18\x05 \x01(\r\x12\x30\n\rbayer_pattern\x18\x06 \x01(\x0e\x32\x19.isppipeline.BayerPattern\x12\x11\n\tbit_depth\x18\x07 \x01(\r\"\xa5\x02\n\nDataPacket\x12\x41\n\x15\x63\x61pture_image_command\x18\x01 \x01(\x0b\x32 .isppipeline.CaptureImageCommandH\x00\x12\x34\n\x0eimage_response\x18\x02 \x01(\x0b\x32\x1a.isppipeline.ImageResponseH\x00\x12L\n\x1bread_isp_parameters_command\x18\x03 \x01(\x0b\x32%.isppipeline.ReadISPParametersCommandH\x00\x12\x45\n\x17isp_parameters_response\x18\x04 \x01(\x0b\x32\".isppipeline.ISPParametersResponseH\x00\x42\t\n\x07payload*6\n\x0c\x42\x61yerPattern\x12\x08\n\x04RGGB\x10\x00\x12\x08\n\x04\x42GGR\x10\x01\x12\x08\n\x04GBRG\x10\x02\x12\x08\n\x04GRBG\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.protocols_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BAYERPATTERN._serialized_start=821
  _BAYERPATTERN._serialized_end=875
  _CAPTUREIMAGECOMMAND._serialized_start=41
  _CAPTUREIMAGECOMMAND._serialized_end=110
  _READISPPARAMETERSCOMMAND._serialized_start=112
  _READISPPARAMETERSCOMMAND._serialized_end=155
  _ISPPARAMETERS._serialized_start=157
  _ISPPARAMETERS._serialized_end=246
  _ISPPARAMETERSRESPONSE._serialized_start=248
  _ISPPARAMETERSRESPONSE._serialized_end=352
  _IMAGERESPONSE._serialized_start=355
  _IMAGERESPONSE._serialized_end=523
  _DATAPACKET._serialized_start=526
  _DATAPACKET._serialized_end=819
# @@protoc_insertion_point(module_scope)
